### ISSUE TITLE
VyperDeployer could not deploy contract with vyper > 0.3.7

### ISSUE THREAD

**Issue by r4VP4** [0xKitsune/Foundry-Vyper#7]
I tried several combinations (using pyenv for the different python versions):
python 3.9.15 vyper 0.3.7: worked for me!
python 3.10.12 vyper 0.3.7: worked for me!
python 3.10.12 vyper 0.3.8: forge test --> [FAIL. Reason: Setup failed: VyperDeployer could not deploy contract]
python 3.10.12 vyper 0.3.9: forge test --> [FAIL. Reason: Setup failed: VyperDeployer could not deploy contract]
python 3.11.4 vyper 0.3.8: forge test --> [FAIL. Reason: Setup failed: VyperDeployer could not deploy contract]
python 3.11.4 vyper 0.3.9: forge test --> [FAIL. Reason: Setup failed: VyperDeployer could not deploy contract]

seems vyper > 0.3.7 isn't working

**Comment by pcaversaccio** [comment]
FWIW, my forked [`VyperDeployer`](https://github.com/pcaversaccio/snekmate/blob/main/lib/utils/VyperDeployer.sol) is extensively tested and works smoothly.

**Comment by 0xKitsune** [comment]
Thanks for linking your fork @pcaversaccio. This repo needs to be updated and I would recommend using [snekmate's VyperDeployer](https://github.com/pcaversaccio/snekmate/blob/main/lib/utils/VyperDeployer.sol) at the moment.

**Comment by pcaversaccio** [comment]
For anyone landing in this issue, I upgraded snekmate's VyperDeployer further, to allow for configuration of the EVM version: https://github.com/pcaversaccio/snekmate/pull/161. Please note that since Vyper version `0.3.8`, the default EVM version is `shanghai`.
